compressionLevel: mixed

enableGlobalCache: false

enableTelemetry: false

nodeLinker: node-modules

npmMinimalAgeGate: 10080

npmPreapprovedPackages:
  - "@injpass/connector"
  - "@xmtp/node-bindings"
  - "@xmtp/wasm-bindings"
  - "@xmtp/node-sdk"

npmRegistryServer: "https://registry.npmjs.org"

yarnPath: .yarn/releases/yarn-4.10.3.cjs
